version: "3.0"

services:
  django:
    image: aivdl.docker.aiv.ai/graphql-django-server:0.1
    container_name: aiv-graphql-server
    env_file:
      - ./.env
    command: bash -ic "python /graphql_server/manage.py makemigrations && python /graphql_server/manage.py migrate && python /graphql_server/manage.py runserver 0.0.0.0:8001"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /etc/localtime:/etc/localtime # for time sync
      - .:/graphql_server
