# Generated by Django 4.2.1 on 2023-05-18 06:04

import athena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, validators=[athena.models.project_name_cannont_be])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1500)),
            ],
            options={
                'db_table': 'ProjectDB',
            },
        ),
        migrations.CreateModel(
            name='TrainStepLogDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.projectdb')),
            ],
            options={
                'db_table': 'TrainStepLogDB',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='TrainExpDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.projectdb')),
            ],
            options={
                'db_table': 'TrainExpDB',
            },
        ),
        migrations.CreateModel(
            name='TrainEpochLogDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('epoch_log', models.JSONField(default=dict)),
                ('_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.projectdb')),
            ],
            options={
                'db_table': 'TrainEpochLogDB',
                'ordering': ['epoch'],
            },
        ),
    ]
