# Generated by Django 4.0 on 2023-05-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcheckdb',
            old_name='health_check',
            new_name='health',
        ),
    ]
